### ISSUE TITLE
New column ScreeningOutput.alignmentSuccess?

### ISSUE THREAD

**Issue by KarlLevik** [ispyb/ispyb-database-modeling#18]
We were wondering if it would make sense to have a new column `ScreeningOutput.alignmentSuccess`? This would be similar to existing columns `indexingSuccess` and `strategySuccess` in the same table. Both these have datatype tinyint(1), so are basically booleans, and this is what we would like for `alignmentSuccess` as well.

This idea originated from @graeme-winter 

What are your thoughts? @antolinos @stufisher @olofsvensson or others?

**Comment by delageniere** [comment]
It's ok for us.
Could be a good idea for later on (with low priority) to refactor the Screening tables.

**Comment by KarlLevik** [comment]
https://github.com/ispyb/ISPyB/pull/307
