### ISSUE TITLE
Add a new field in BLSession table to handle nb of reimbursed dewars

### ISSUE THREAD

**Issue by delageniere** [ispyb/ispyb-database-modeling#21]
At ESRF we are asked to track in ISPyB the number of reimbursed dewars authorized in the User Portal software.
Therefore we will need an extra field in BLSession table:
nbReimbursedDewars 

This number will be defined in the User Portal according to the type of experiment, to the nb of reimbursed users and to a maximum possible. This number is linked to a session and can change between 2 sessions of the same proposal (currently between 0 and 4).

**Comment by delageniere** [comment]
We will have also to add a new field in Dewar, to mark the Dewar/Parcel/Box as reimbursed.
isReimbursed tinyInt

**Comment by KarlLevik** [comment]
We've discussed this briefly at Diamond. We don't have any objections to adding it, so feel free to go ahead.

**Comment by delageniere** [comment]
Done.
