### ISSUE TITLE
Extend fileType enum in table DataCollectionFileAttachment

### ISSUE THREAD

**Issue by KarlLevik** [ispyb/ispyb-database-modeling#7]
In _DataCollectionFileAttachment_ table we would like to extend the _fileType_ enum, and I've also included a comment to better document what the different options are for:

```sql
ALTER TABLE DataCollectionFileAttachment MODIFY fileType enum('snapshot', 'log', 'xy', 'recip') 
COMMENT 'snapshot: image file, usually of the sample. 
log: a text file with logging info. 
xy: x and y data in text format. 
recip: a compressed csv file with reciprocal space coordinates.';
```

Can this be merged into the official schema?

**Comment by antolinos** [comment]
It has sense to us.
If nobody is against and you want to consolidate such change into the ISPyB database I will ask @delageniere to add some documentation in the ISPyB webpage (readme.md) about how to integrate changes in the data model on ISPyB.
